version: "3.2"
services:
  mongocfg_rs1_1:
    image: walter-mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongocfg_rs1_1:/data/db
      - mongocfg_rs1_1_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 1

  mongocfg_rs1_2:
    image: walter-mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongocfg_rs1_2:/data/db
      - mongocfg_rs1_2_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 2

  mongocfg_rs1_3:
    image: walter-mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongocfg_rs1_3:/data/db
      - mongocfg_rs1_3_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 3

  mongosrd_rs2_1:
    image: walter-mongo:3.4.10    
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongosrd_rs2_1:/data/db
      - mongosrd_rs2_1_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 1

  mongosrd_rs2_2:
    image: walter-mongo:3.4.10
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongosrd_rs2_2:/data/db
      - mongosrd_rs2_2_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 2

  mongosrd_rs2_3:
    image: walter-mongo:3.4.10
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongosrd_rs2_3:/data/db
      - mongosrd_rs2_3_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 3

  mongos_1:
    image: walter-mongo:3.4.10
    command: mongos --configdb rs1/mongocfg_rs1_1,mongocfg_rs1_2,mongocfg_rs1_3:27017 --port 27017
    volumes:
      - mongos_1:/data/db
      - ./mongo/rs_inits:/rs_inits
      - ./walter-02:/webapp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.mongos == 1

  mongos_2:
    image: walter-mongo:3.4.10
    command: mongos --configdb rs1/mongocfg_rs1_1,mongocfg_rs1_2,mongocfg_rs1_3:27017 --port 27017
    volumes:
      - mongos_2:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.mongos == 2

  swift_01:
    image: walter-swift
    command: bash -c "chown -R swift:swift /srv && /usr/bin/supervisord -c /etc/swift/supervisord.conf && sleep 3 && tail -n 0 -f /var/log/syslog"
    volumes:
      - swift_01:/srv
      - ./swift/configs/swift_01:/etc/swift
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 6010
        published: 6010
        protocol: tcp
        mode: host
      - target: 6011
        published: 6011
        protocol: tcp
        mode: host
      - target: 6012
        published: 6012
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 1

  swift_02:
    image: walter-swift
    command: bash -c "chown -R swift:swift /srv && /usr/bin/supervisord -c /etc/swift/supervisord.conf && sleep 3 && tail -n 0 -f /var/log/syslog"
    volumes:
      - swift_02:/srv
      - ./swift/configs/swift_02:/etc/swift
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 6010
        published: 6010
        protocol: tcp
        mode: host
      - target: 6011
        published: 6011
        protocol: tcp
        mode: host
      - target: 6012
        published: 6012
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 2

  swift_03:
    image: walter-swift
    command: bash -c "chown -R swift:swift /srv && /usr/bin/supervisord -c /etc/swift/supervisord.conf && sleep 3 && tail -n 0 -f /var/log/syslog"
    volumes:
      - swift_03:/srv
      - ./swift/configs/swift_03:/etc/swift
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 6010
        published: 6010
        protocol: tcp
        mode: host
      - target: 6011
        published: 6011
        protocol: tcp
        mode: host
      - target: 6012
        published: 6012
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 3

  elastic_01:
    image: walter-elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_01"
    volumes:
      - ./elastic/config/elastic_01:/usr/share/elasticsearch/config
      - elastic_01_data:/usr/share/elasticsearch/data
      - elastic_01_logs:/usr/share/elasticsearch/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 1

  elastic_02:
    image: walter-elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_02"
    volumes:
      - ./elastic/config/elastic_02:/usr/share/elasticsearch/config
      - elastic_02_data:/usr/share/elasticsearch/data
      - elastic_02_logs:/usr/share/elasticsearch/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 2

  nodejs_01:
    image: walter-node:6.12
    command: bash -c "cd /webapp/walter-02/server && npm start"
    volumes:
      - nodejs_01_logs:/webapp/walter-02/server/logs
    ports:
      - target: 3333
        published: 3000
        protocol: tcp
        mode: host
    environment:
      - NODE_ENV=production
      - MONGO_HOST_NAME=mongos_1
      - SWIFT_HOST_NAME=swift_01
      - ELASTIC_HOST_NAME=elastic_01
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodejs.node == 1

  nodejs_02:
    image: walter-node:6.12
    command: bash -c "cd /webapp/walter-02/server && npm start"
    volumes:
      - nodejs_02_logs:/webapp/walter-02/server/logs
    ports:
      - target: 3333
        published: 3000
        protocol: tcp
        mode: host
    environment:
      - NODE_ENV=production
      - MONGO_HOST_NAME=mongos_2
      - SWIFT_HOST_NAME=swift_02
      - ELASTIC_HOST_NAME=elastic_02
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodejs.node == 2

volumes:
  mongocfg_rs1_1:
  mongocfg_rs1_1_logs:
  mongocfg_rs1_2:
  mongocfg_rs1_2_logs:
  mongocfg_rs1_3:
  mongocfg_rs1_3_logs:
  mongosrd_rs2_1:
  mongosrd_rs2_1_logs:
  mongosrd_rs2_2:
  mongosrd_rs2_2_logs:
  mongosrd_rs2_3:
  mongosrd_rs2_3_logs:
  mongos_1:
  mongos_2:
  swift_01:
  swift_02:
  swift_03:
  elastic_01_data:
  elastic_01_logs:
  elastic_02_data:
  elastic_02_logs:
  nodejs_01_logs:
  nodejs_02_logs:

networks:
  default:
    external:
      name: "walter_overlay"
