version: "3"
services:
  mongocfg_rs1_1:
    image: mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --port 27017
    volumes:
      - mongocfg_rs1_1:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 1

  mongocfg_rs1_2:
    image: mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --port 27017
    volumes:
      - mongocfg_rs1_2:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 2

  mongocfg_rs1_3:
    image: mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --port 27017
    volumes:
      - mongocfg_rs1_3:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 3

  mongosrd_rs2_1:
    image: mongo:3.4.10    
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --port 27017
    volumes:
      - mongosrd_rs2_1:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 1

  mongosrd_rs2_2:
    image: mongo:3.4.10
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --port 27017
    volumes:
      - mongosrd_rs2_2:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 2

  mongosrd_rs2_3:
    image: mongo:3.4.10
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --port 27017
    volumes:
      - mongosrd_rs2_3:/data/db
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 3

  mongos_1:
    image: mongo:3.4.10
    command: mongos --configdb rs1/mongocfg_rs1_1,mongocfg_rs1_2,mongocfg_rs1_3:27017 --port 27017
    ports:
      - 27017:27017
    volumes:
      - mongos_1:/data/db
      - ./mongo/rs_inits:/rs_inits
    depends_on:
      - mongocfg_rs1_1
      - mongocfg_rs1_2
      - mongocfg_rs1_3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.mongos == 1

  mongos_2:
    image: mongo:3.4.10
    command: mongos --configdb rs1/mongocfg_rs1_1,mongocfg_rs1_2,mongocfg_rs1_3:27017 --port 27017
    ports:
      - 27018:27017
    volumes:
      - mongos_2:/data/db
      - ./mongo/rs_inits:/rs_inits
    depends_on:
      - mongocfg_rs1_1
      - mongocfg_rs1_2
      - mongocfg_rs1_3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.mongos == 2

  swift_01:
    image: morrisjobke/docker-swift-onlyone
    volumes:
      - swift_01:/srv
    ports:
      - 8080:8080
      - 6010:6010
      - 6011:6011
      - 6012:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 1

  swift_02:
    image: morrisjobke/docker-swift-onlyone
    volumes:
      - swift_02:/srv
    ports:
      - 8081:8080
      - 6020:6010
      - 6021:6011
      - 6022:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 2

  swift_03:
    image: morrisjobke/docker-swift-onlyone
    volumes:
      - swift_03:/srv
    ports:
      - 8082:8080
      - 6030:6010
      - 6031:6011
      - 6032:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 3

  elastic_01:
    image: elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_01"
    volumes:
      - ./elastic/conf:/usr/share/elasticsearch/config
      - elastic_01:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 1

  elastic_02:
    image: elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_02"
    volumes:
      - ./elastic/conf:/usr/share/elasticsearch/config
      - elastic_02:/usr/share/elasticsearch/data
    depends_on:
      - elastic_01
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 2

  elastic_03:
    image: elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_03"
    volumes:
      - ./elastic/conf:/usr/share/elasticsearch/config
      - elastic_03:/usr/share/elasticsearch/data
    depends_on:
      - elastic_01
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 3

  nodejs_01:
    image: walter-node:6.12
    command: bash -c "cd /webapp/walter-02/server && npm start"
    volumes:
      - ./node/conf:/webapp/walter-02/server/configs
    ports:
      - 3000:3333
    depends_on:
      - mongos_1
      - swift_01
      - elastic_01
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodejs.node == 1

  nodejs_02:
    image: walter-node:6.12
    command: bash -c "cd /webapp/walter-02/server && npm start"
    volumes:
      - ./node/conf:/webapp/walter-02/server/configs
    ports:
      - 3001:3333
    depends_on:
      - mongos_2
      - swift_02
      - elastic_02
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodejs.node == 2

volumes:
  mongocfg_rs1_1:
  mongocfg_rs1_2:
  mongocfg_rs1_3:
  mongosrd_rs2_1:
  mongosrd_rs2_2:
  mongosrd_rs2_3:
  mongos_1:
  mongos_2:
  swift_01:
  swift_02:
  swift_03:
  elastic_01:
  elastic_02:
  elastic_03:
  nodejs_01:
  nodejs_02: