version: "3"
services:
  mongocfg_rs1_1:
    image: walter-mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongocfg_rs1_1:/data/db
      - mongocfg_rs1_1_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 1

  mongocfg_rs1_2:
    image: walter-mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongocfg_rs1_2:/data/db
      - mongocfg_rs1_2_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 2

  mongocfg_rs1_3:
    image: walter-mongo:3.4.10
    command: mongod --configsvr --replSet rs1 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongocfg_rs1_3:/data/db
      - mongocfg_rs1_3_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs1 == 3

  mongosrd_rs2_1:
    image: walter-mongo:3.4.10    
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongosrd_rs2_1:/data/db
      - mongosrd_rs2_1_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 1

  mongosrd_rs2_2:
    image: walter-mongo:3.4.10
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongosrd_rs2_2:/data/db
      - mongosrd_rs2_2_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 2

  mongosrd_rs2_3:
    image: walter-mongo:3.4.10
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=-1 --port 27017
    volumes:
      - mongosrd_rs2_3:/data/db
      - mongosrd_rs2_3_logs:/var/log/mongodb
      - ./mongo/rs_inits:/rs_inits
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica.rs2 == 3

  mongos_1:
    image: walter-mongo:3.4.10
    command: mongos --configdb rs1/mongocfg_rs1_1,mongocfg_rs1_2,mongocfg_rs1_3:27017 --port 27017
    volumes:
      - mongos_1:/data/db
      - ./mongo/rs_inits:/rs_inits
      - ./walter-02:/webapp
    ports:
      - 27017:27017
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.mongos == 1

  mongos_2:
    image: walter-mongo:3.4.10
    command: mongos --configdb rs1/mongocfg_rs1_1,mongocfg_rs1_2,mongocfg_rs1_3:27017 --port 27017
    volumes:
      - mongos_2:/data/db
      - ./mongo/rs_inits:/rs_inits
    ports:
      - 27018:27017
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.mongos == 2

  swift_01:
    image: walter-swift
    volumes:
      - swift_01:/srv
    ports:
      - 8080:8080
      - 6010:6010
      - 6011:6011
      - 6012:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 1

  swift_02:
    image: walter-swift
    volumes:
      - swift_02:/srv
    ports:
      - 6020:6010
      - 6021:6011
      - 6022:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 2

  swift_03:
    image: walter-swift
    volumes:
      - swift_03:/srv
    ports:
      - 6030:6010
      - 6031:6011
      - 6032:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 3

  elastic_01:
    image: walter-elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_01"
    ports:
      - 9200:9200
    volumes:
      - ./elastic/config/elastic_01:/usr/share/elasticsearch/config
      - elastic_01_data:/usr/share/elasticsearch/data
      - elastic_01_logs:/usr/share/elasticsearch/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 1

  elastic_02:
    image: walter-elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_02"
    volumes:
      - ./elastic/config/elastic_02:/usr/share/elasticsearch/config
      - elastic_02_data:/usr/share/elasticsearch/data
      - elastic_02_logs:/usr/share/elasticsearch/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 2

  elastic_03:
    image: walter-elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_03"
    volumes:
      - ./elastic/config/elastic_03:/usr/share/elasticsearch/config
      - elastic_03_data:/usr/share/elasticsearch/data
      - elastic_03_logs:/usr/share/elasticsearch/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 3

  nodejs_01:
    image: walter-node:6.12
    command: bash -c "cd /webapp/walter-02/server && npm start"
    volumes:
      - nodejs_01:/webapp
    ports:
      - 3000:3333
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodejs.node == 1

  nodejs_02:
    image: walter-node:6.12
    command: bash -c "cd /webapp/walter-02/server && npm start"
    volumes:
      - nodejs_02:/webapp
    ports:
      - 3001:3333
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodejs.node == 2

volumes:
  mongocfg_rs1_1:
  mongocfg_rs1_1_logs:
  mongocfg_rs1_2:
  mongocfg_rs1_2_logs:
  mongocfg_rs1_3:
  mongocfg_rs1_3_logs:
  mongosrd_rs2_1:
  mongosrd_rs2_1_logs:
  mongosrd_rs2_2:
  mongosrd_rs2_2_logs:
  mongosrd_rs2_3:
  mongosrd_rs2_3_logs:
  mongos_1:
  mongos_2:
  swift_01:
  swift_02:
  swift_03:
  elastic_01_data:
  elastic_01_logs:
  elastic_02_data:
  elastic_02_logs:
  elastic_03_data:
  elastic_03_logs:
  nodejs_01:
  nodejs_02:

networks:
  default:
    external:
      name: "walter_overlay"
