version: "3"
services:
  elstic_01:
    image: elasticsearch:5.6
    environment:
      _JAVA_OPTIONS: "-Xms128m -Xmx128m"
    volumes:
      - ./conf:/etc/elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 1

  elstic_02:
    image: elasticsearch:5.6
    environment:
      _JAVA_OPTIONS: "-Xms128m -Xmx128m"
    volumes:
      - ./conf:/etc/elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 2

  elstic_03:
    image: elasticsearch:5.6
    environment:
      _JAVA_OPTIONS: "-Xms128m -Xmx128m"
    volumes:
      - ./conf:/etc/elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 3
