version: "3"
services:
  elastic_01:
    image: elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_01"
    volumes:
      - ./conf:/usr/share/elasticsearch/config
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 1

  elastic_02:
    image: elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_02"
    volumes:
      - ./conf:/usr/share/elasticsearch/config
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 2

  elastic_03:
    image: elasticsearch:5.6
    environment:
      NODE_NAME: "elastic_03"
    volumes:
      - ./conf:/usr/share/elasticsearch/config
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.elastic.node == 3
