version: "3"
services:
  swift_01:
    image: morrisjobke/docker-swift-onlyone
    volumes:
      - swift_01:/srv
    ports:
      - 8080:8080
      - 6010:6010
      - 6011:6011
      - 6012:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 1

  swift_02:
    image: morrisjobke/docker-swift-onlyone
    volumes:
      - swift_02:/srv
    ports:
      - 8081:8080
      - 6020:6010
      - 6021:6011
      - 6022:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 2

  swift_03:
    image: morrisjobke/docker-swift-onlyone
    volumes:
      - swift_03:/srv
    ports:
      - 8082:8080
      - 6030:6010
      - 6031:6011
      - 6032:6012
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swift.node == 3

volumes:
  swift_01:
  swift_02:
  swift_03: