version: "3"
services:
  mongo_01:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    volumes:
      - ./mongo/tmp:/host_tmp

  swift_01:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - 8080:8080
    volumes:
      - ./swift/tmp:/host_tmp

  elastic_01:
    image: walter-elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elastic/tmp:/host_tmp

  nodejs_01:
    image: walter-nodejs
    command: bash -c "cd /webapp/walter-02/server/lib/configs && cp server.js.dist server.js && npm start"
    volumes:
      - /tmp:/host_tmp
    ports:
      - 3000:3333
    environment:
      - NODE_ENV=production
      - MONGO_HOST_NAME=192.168.56.13
      - SWIFT_HOST_NAME=192.168.56.13
      - ELASTIC_HOST_NAME=192.168.56.13
      - LANG=ja_JP.UTF-8
    volumes:
      - ./nodejs/tmp:/host_tmp
